spring.application.name=proyecto-camel
sipap.productor-a.periodo=4000
sipap.productor-b.periodo=4000
sipap.productores-timer.habilitados=false
sipap.jms.habilitado=true
sipap.artemis.broker-url=${ARTEMIS_URL:tcp://localhost:61616}
sipap.cola.entrada=sipap.entrada
sipap.cola.itau=sipap.itau
sipap.cola.atlas=sipap.atlas
sipap.cola.familiar=sipap.familiar
sipap.banco-mock.base-url=${BANCO_MOCK_URL:http://localhost:8081}
sipap.zona-horaria=America/Asuncion
sipap.monto-maximo=10000000
camel.component.jms.acknowledgement-mode=1
camel.component.jms.test-connection-on-startup=true
camel.component.jms.concurrent-consumers=1
camel.component.jms.cache-level-name=CACHE_CONNECTION
